spring:
  application:
    name: events-kata
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydatabase}
    username: ${POSTGRES_USERNAME:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  threads:
    virtual:
      enabled: true
  data:
    redis:
      repositories.enabled: true
      host: localhost
      port: 6379
  product.update.topic: product.update